### ISSUE TITLE
Add Open Rec time for Rockwell NORTH CT and Rockwell SOUTH CT

### ISSUE THREAD

**Issue by aoranwu** [williamshen-nz/recschedule-website#2]
When event for Rockwell NORTH CT or Rockwell SOUTH CT is Open Rec, it's highly possible that we can use it as badminton court. It would be nice if time for such events is added to the webpage as well for people's reference.

By the way, your website really saves our trouble to go through the whole pdf. It helps a lot. Thanks!

**Comment by williamshen-nz** [comment]
Hi, glad you find the website useful!

I probably won't be able to add this feature anytime in the next month, but feel free to contribute and open a PR in the meantime

**Pre-requisites**
- [x] Convert a PDF with Rockwell that is just Open Rec to text using`pdftotext` (what the bash script uses)
- [x] Understand how the converter represents those entries

**Changes Required:**
- [x] Update parsing logic and regex here to check for Rockwell and Open Rec only (negative match any other sports): https://github.com/williamshen-nz/recschedule-website/blob/main/recschedule_website/parser.py#L7-L90
- [x] Add a 'shared' field to the `Schedule` object so we can disambiguate from badminton only vs general Open rec sessions: https://github.com/williamshen-nz/recschedule-website/blob/main/recschedule_website/types.py#L36-L41
    - [x] Dump those to HTML like `2:00 PM - 6:00 PM, Rockwell South CT (Shared) [Google Cal]`
    - [x] Question mark tooltip (?) over shared when on hover or click says that it is shared session with other sport, so space not guaranteed would be nice.
- [x] Add new PDF to unit tests with a PDF schedule that entries where it is Rockwell with just open rec. e.g. [recschedule-with-rockwell-openrec.pdf](https://github.com/williamshen-nz/recschedule-website/files/9746647/recschedule-with-rockwell-openrec.pdf)

To check the existing functionality hasn't broken, you can run pytest on the unit tests in `tests/`. I think they should perform a parsing logic on an old `recschedule.pdf` and check the output is as expected.

**Comment by williamshen-nz** [comment]
My todos:

- [x] Clean up
- [x] Verification
- [x] Small tooltip for shared sessions

**Comment by williamshen-nz** [comment]
Cleaned up and everything. Deploy to beta and observe.

**Comment by williamshen-nz** [comment]
Deployed to https://shen.nz/badminton-beta

For some reason, the shared session font is rendered smaller on my Android. It's fine when testing mobile mode in Chrome, or on iOS

Maybe it's a cache issue.

**Comment by williamshen-nz** [comment]
Android Chrome decides to do font boosting which is causing the issue: https://stackoverflow.com/questions/11289166/chrome-on-android-resizes-font

**TODOs:**
- [x] Apply the fix
- [ ] Test it for a few days
- [x] Move the beta to main

PR #3 did the prior stuff.

**Comment by williamshen-nz** [comment]
I closed off the beta endpoint.

Tried applying the fix, check in later as I'm too busy with other things
